import type { Series } from "../types";

// ROMANCE — Two strangers, one city-wide blackout, one night to fall.
export const afterglow: Series = {
  id: "s-afterglow",
  slug: "afterglow",
  title: "Afterglow",
  genre: "Romance",
  tagline: "The lights went out across the city. For one night, so did the rest of the world.",
  premise:
    "When a grid failure traps the last two commuters inside a shuttered Mumbai metro station, Ira — who flies abroad at dawn for good — and Kabir — who has never left — have exactly one night and a dying phone battery between them. They agree to be honest, because strangers can afford to be.",
  synopsis:
    "Ira has spent a year packing her whole life into two suitcases and a one-way ticket. Kabir has spent the same year not leaving the city that raised him. A transformer fire plunges Mumbai into darkness and locks them both behind the gates of an underground platform until morning. With a single power bank, an emergency light, and a vending machine they have to bribe with coins and faith, they make a pact: total honesty, no last names, no tomorrow. Over ten episodes the night becomes a confessional — first loves, worst regrets, the dreams they outgrew and the ones they're still scared to say aloud. By the time the lights flicker back, the only thing more terrifying than the dark is the daylight that will separate them. A love story measured not in years but in the warmth a moment leaves behind.",
  posterConcept:
    "Two silhouettes sitting a careful distance apart on the edge of an empty platform, lit by a single amber emergency lamp; warm gold light pooling on cold tile, the tunnel mouth pure black behind them. Negative space and one shared circle of light.",
  year: 2026,
  maturity: "13+",
  avgLength: "85s",
  tags: ["Slow-burn", "One night", "Bittersweet", "Two-hander"],
  score: 91,
  art: { base: "#140a06", accent: "#ff9e4d", accent2: "#e8526a", glow: "#ffd6a0", motif: "horizon" },
  cast: [
    { name: "Anaya Kulkarni", character: "Ira", initials: "IR" },
    { name: "Rohan D'Souza", character: "Kabir", initials: "KB" },
    { name: "Voice only", character: "The Station Announcer", initials: "SA" },
  ],
  episodes: [
    {
      number: 1,
      title: "Last Train Cancelled",
      logline: "The grid dies, the gates lock, and two strangers realize they're not leaving.",
      runtimeSec: 0,
      cliffhanger: "The emergency light clicks on, framing them both. Kabir grins: 'So. Stuck-with-a-stranger. Want to make it interesting?'",
      beats: [
        { kind: "slate", sec: 3, text: "AFTERGLOW — Ep. 1: Last Train Cancelled" },
        { kind: "scene", sec: 6, slug: "INT. METRO PLATFORM — NIGHT", text: "An empty underground platform. The departure board freezes, then dies. Every light goes with it.", camera: "Wide, the dark swallowing the tunnel mouth." },
        { kind: "sfx", sec: 4, text: "A deep electrical thunk. The hum of the city above cuts to nothing." },
        { kind: "dialogue", sec: 6, speaker: "IRA", paren: "(into dead phone)", text: "No. No no no. Not tonight. I have a flight in nine hours.", camera: "Phone glow dies on her face." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", paren: "(somewhere in the dark)", text: "Gates are down. Whole grid, I think. We're not getting out till they reset it.", camera: "Voice before the face." },
        { kind: "action", sec: 5, text: "A battery-powered emergency lamp stutters to life — one warm circle in all that cold blue-black.", camera: "Amber bloom revealing two strangers." },
        { kind: "cliffhanger", sec: 9, text: "Kabir steps into the light, grinning. 'Okay. Stuck-with-a-stranger till sunrise. Want to make it interesting? No last names. No lies. Nobody we'll ever see again.'", camera: "Two-shot in the lamp's glow. Cut." },
      ],
    },
    {
      number: 2,
      title: "The Rules",
      logline: "They invent a game: total honesty, because it costs nothing by morning.",
      runtimeSec: 0,
      cliffhanger: "Ira: 'Fine. First truth. I'm not scared of the dark.' Kabir: 'Then why are you sitting this close to me?'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 2: The Rules" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM EDGE — NIGHT", text: "Two strangers settle onto the cold platform lip, a careful arm's length apart.", camera: "Symmetrical two-shot, the lamp between them." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "Rules. One: only true things. Two: you can pass, but only three times. Three: at sunrise it never happened.", camera: "He counts on his fingers, lamp-lit." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "You've clearly done this before.", camera: "Ira, half a smile." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "Never. I've just always wanted somewhere it was safe to be honest. Turns out it's here. With you. In a blackout.", camera: "Push in, gentle." },
        { kind: "action", sec: 5, text: "Ira pulls her knees up, decides something, and shifts an inch closer to the light. To him.", camera: "Insert: the small distance closing." },
        { kind: "cliffhanger", sec: 9, text: "IRA: 'Fine. First truth — I'm not scared of the dark.' KABIR: 'Then why'd you just move closer to me?' She has no answer. Neither does the night.", camera: "Hold on the two of them. Cut." },
      ],
    },
    {
      number: 3,
      title: "One-Way Ticket",
      logline: "Ira admits she's leaving the country at dawn — for good.",
      runtimeSec: 0,
      cliffhanger: "Kabir, quietly: 'So whatever this is, it has an expiry time.' Ira: 'Six forty a.m.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 3: One-Way Ticket" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM — NIGHT", text: "The vending machine hums on emergency power. They share a packet of biscuits like it's a feast.", camera: "Cozy close-up, crumbs and lamplight." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "Your turn. Why the flight? Holiday? Running away? Running toward?", camera: "He breaks a biscuit, offers half." },
        { kind: "dialogue", sec: 7, speaker: "IRA", text: "One-way. New job, new country, new everything. I've spent a year fitting my life into two suitcases.", camera: "Ira looking at the dark tunnel like a door." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "And the part of your life that didn't fit?", camera: "Soft, careful." },
        { kind: "dialogue", sec: 6, speaker: "IRA", paren: "(quiet)", text: "I left it. That was sort of the point.", camera: "She won't meet his eyes." },
        { kind: "cliffhanger", sec: 9, text: "KABIR: 'So whatever this is — it has an expiry time.' IRA: 'Six forty a.m.' The lamp seems to dim a little, though it doesn't.", camera: "Two-shot, the gap between them suddenly loud. Cut." },
      ],
    },
    {
      number: 4,
      title: "The Boy Who Stayed",
      logline: "Kabir confesses he's never once left the city — and why.",
      runtimeSec: 0,
      cliffhanger: "Ira: 'You're not stuck here because of him. You're staying so you don't have to find out who you are without him.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 4: The Boy Who Stayed" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM — NIGHT", text: "Ira's turn to ask. The roles quietly reverse.", camera: "Reverse the two-shot framing from Ep. 3." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "My turn. You said you've never left Mumbai. Not once? Not even a train out?", camera: "Ira, genuinely surprised." },
        { kind: "dialogue", sec: 7, speaker: "KABIR", text: "My father got sick the year I was supposed to leave for college. I stayed. He got better. I just... never restarted the leaving.", camera: "Kabir turning a coin over and over." },
        { kind: "dialogue", sec: 5, speaker: "IRA", text: "That was years ago. He's fine now?", camera: "Gentle." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "He's great. He keeps asking why I'm still here. I keep not answering.", camera: "A small, honest laugh that isn't really one." },
        { kind: "cliffhanger", sec: 9, text: "IRA, soft but exact: 'You're not staying for him anymore. You're staying so you never have to find out who you are without this city.' Kabir goes very still.", camera: "Push in on his face as it lands. Cut." },
      ],
    },
    {
      number: 5,
      title: "Power Bank",
      logline: "One charge, one phone, one song. They decide what's worth the battery.",
      runtimeSec: 0,
      cliffhanger: "The song ends. Ira realizes they've moved close enough to share the same circle of light. Neither moves back.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 5: Power Bank" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM — DEEP NIGHT", text: "A single power bank between them, 14% on Kabir's phone. A decision.", camera: "Macro on the battery icon." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "Fourteen percent. We could save it for the morning. Or we could spend it on something stupid right now.", camera: "He holds the phone up like an offering." },
        { kind: "dialogue", sec: 5, speaker: "IRA", text: "Define stupid.", camera: "Ira, daring him." },
        { kind: "action", sec: 6, text: "Kabir thumbs through, picks a song — tinny through a phone speaker, enormous in the empty station.", camera: "Sound blooms into the tunnel's reverb." },
        { kind: "action", sec: 6, text: "They don't dance, exactly. They just sway, sitting, shoulders finding each other.", camera: "Slow orbit, the lamp glow soft on both faces." },
        { kind: "cliffhanger", sec: 9, text: "The song fades. Ira realizes, with a small shock, that they've drifted into the same circle of light. Close enough to feel warmth. Neither of them moves back.", camera: "Hold on the shrinking distance. Cut." },
      ],
    },
    {
      number: 6,
      title: "Worst Thing You've Done",
      logline: "The honesty game finds its edge. They each spend a 'pass' — then don't.",
      runtimeSec: 0,
      cliffhanger: "Kabir tells the truth he's never told anyone. Ira reaches across the dark and takes his hand instead of answering.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 6: Worst Thing You've Done" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM — DEEP NIGHT", text: "The game has run out of easy questions.", camera: "Tighter now, the lamp lower." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "Worst thing you've ever done. And you can't pass. We're past passing.", camera: "Ira, no smile now." },
        { kind: "dialogue", sec: 8, speaker: "KABIR", text: "I told my dad I stayed for him. The truth is I was terrified to fail somewhere no one knew my name. I used his illness as a place to hide. I've never said that out loud.", camera: "Kabir to the dark, not to her." },
        { kind: "action", sec: 5, text: "Silence. The honest kind. Ira doesn't fill it with comfort.", camera: "Hold on his face, then hers." },
        { kind: "dialogue", sec: 5, speaker: "IRA", paren: "(barely)", text: "Mine's similar. I'm not chasing a dream. I'm outrunning one that died.", camera: "Profile, lamp-rim light." },
        { kind: "cliffhanger", sec: 9, text: "Instead of trading more words, Ira reaches across the dark and takes his hand. The honesty game becomes something with no rules at all.", camera: "Macro: two hands, one circle of light. Cut." },
      ],
    },
    {
      number: 7,
      title: "If We'd Met Sooner",
      logline: "They let themselves imagine the version of this with more than one night.",
      runtimeSec: 0,
      cliffhanger: "Kabir: 'In another life I'd ask for your number.' Ira: 'In this one?' The emergency lamp flickers — power is coming back.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 7: If We'd Met Sooner" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM — PRE-DAWN", text: "Hands still joined. The dangerous part of the night: hope.", camera: "Soft focus, warm grain." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "Okay, dangerous question. If we'd met a year ago. Before the ticket. Before all of it.", camera: "Ira, playing with fire and knowing it." },
        { kind: "dialogue", sec: 7, speaker: "KABIR", text: "A year ago I'd have been too scared to talk to you on a moving train. It took the whole city shutting down to make me brave.", camera: "A real laugh, finally." },
        { kind: "dialogue", sec: 5, speaker: "IRA", text: "So the blackout's the best thing that's happened to you.", camera: "Teasing, but her eyes aren't." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "In another life, this is the part where I ask for your number.", camera: "Quiet. The question under the question." },
        { kind: "action", sec: 4, text: "Above them, deep in the tunnel — a single light flickers. Then another. The grid is coming back.", camera: "Insert: a far light stuttering awake." },
        { kind: "cliffhanger", sec: 9, text: "IRA, holding his gaze: 'And in this one?' Before he can answer, the platform lights surge half-alive. The night they agreed to forget is almost over.", camera: "Their faces lit by returning fluorescents. Cut." },
      ],
    },
    {
      number: 8,
      title: "Sunrise Clause",
      logline: "The lights are back. The rule said this ends at dawn. Do they keep their own rule?",
      runtimeSec: 0,
      cliffhanger: "The gates grind open. Ira: 'The rule was — at sunrise, it never happened.' Kabir: 'So break the rule.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 8: Sunrise Clause" },
        { kind: "scene", sec: 5, slug: "INT. PLATFORM — DAWN", text: "Harsh ordinary light floods the platform. The magic circle of lamp-glow is gone.", camera: "The romance of the dark replaced by fluorescent reality." },
        { kind: "action", sec: 5, text: "They let go of each other's hands — reflex, embarrassment, the daylight rule.", camera: "Insert: hands separating, an inch that feels like miles." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "So. That's that. The rule was clear. At sunrise it never happened.", camera: "Ira gathering her bag, not looking up." },
        { kind: "dialogue", sec: 6, speaker: "KABIR", text: "We made that rule when we thought you were just a stranger.", camera: "Kabir not moving." },
        { kind: "sfx", sec: 4, text: "A mechanical groan. The station gates begin to grind open." },
        { kind: "cliffhanger", sec: 9, text: "The gates yawn wide, the city pouring grey light through them. KABIR, stepping into her path: 'So break the rule. Stay ten more minutes. Miss one flight. People do it in films all the time.'", camera: "Two-shot against the open gate. Cut." },
      ],
    },
    {
      number: 9,
      title: "Departures",
      logline: "An airport, a clock, a decision that two suitcases can't make for her.",
      runtimeSec: 0,
      cliffhanger: "At the gate, Ira's phone — finally charged — lights up with one text from a number she saved as 'Blackout.' She reads it. She turns around.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 9: Departures" },
        { kind: "scene", sec: 5, slug: "INT. AIRPORT — MORNING", text: "Ira in the security line, two suitcases, a whole life in cold fluorescent order.", camera: "Wide, she is one of a hundred travelers." },
        { kind: "vo", sec: 7, speaker: "IRA", text: "I didn't break the rule. I did the sensible thing. I caught the cab. I came to the airport. I'm so good at leaving I could teach it.", camera: "Her face in the slow shuffle of the queue." },
        { kind: "action", sec: 5, text: "She fingers a metro ticket stub she should have thrown away. She didn't.", camera: "Macro: the kept ticket." },
        { kind: "dialogue", sec: 5, speaker: "GATE ANNOUNCER (V.O.)", text: "Final call. This is the final boarding call for the 6:40 service.", camera: "Insert: the gate sign, 6:40." },
        { kind: "action", sec: 5, text: "Her phone, charged at last, buzzes. One text, from a contact she saved as 'Blackout.'", camera: "Insert: the screen lighting her face." },
        { kind: "cliffhanger", sec: 9, text: "The text: 'You never answered my question. In THIS life. — K.' Ira looks at the gate. At the ticket. At the message. And she steps out of the line.", camera: "She turns against the flow of the crowd. Cut to black." },
      ],
    },
    {
      number: 10,
      title: "Afterglow",
      logline: "Not every love story needs a forever. Some only need an honest night and the courage to admit it mattered.",
      runtimeSec: 0,
      cliffhanger: "Kabir, at the same platform that night: 'You missed your flight.' Ira: 'No. I caught a different one. Same rules?' Kabir: 'New rule. This one doesn't end at sunrise.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 10: Afterglow" },
        { kind: "scene", sec: 5, slug: "INT. METRO PLATFORM — NIGHT", text: "The same platform. Lights working, trains running, the ordinary world restored — and somehow charged.", camera: "Mirror of Ep. 1's opening wide." },
        { kind: "action", sec: 5, text: "Kabir is there, exactly where he was, like he never quite left. He sees her. He can't believe her.", camera: "His face doing all the work." },
        { kind: "dialogue", sec: 5, speaker: "KABIR", text: "You missed your flight.", camera: "Half disbelief, half hope." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "No. I caught a different one. Deferred the job three months. Turns out futures can wait a little.", camera: "Ira, lighter than we've ever seen her." },
        { kind: "vo", sec: 7, speaker: "IRA", text: "We didn't promise forever. We're not stupid. We promised the next three months — honestly, no last names yet, one truth at a time. It's the bravest thing either of us has ever done.", camera: "The two of them on the platform edge, where it started." },
        { kind: "dialogue", sec: 6, speaker: "IRA", text: "Same rules?", camera: "She sits in the old spot." },
        { kind: "cliffhanger", sec: 9, text: "KABIR sits beside her, closer than strangers ever would: 'New rule. This one doesn't end at sunrise.' The next train arrives — and for once, neither of them gets on it. End of Season 1.", camera: "Pull back as the train doors close empty. Warm fade." },
      ],
    },
  ],
};
