import type { Series } from "../types";

// SCI-FI — A grief-tech engineer finds an AI "echo" of herself that shouldn't exist yet.
export const echoProtocol: Series = {
  id: "s-echo-protocol",
  slug: "echo-protocol",
  title: "Echo Protocol",
  genre: "Sci-Fi",
  tagline: "They built software to talk to the dead. Then her own echo logged in.",
  premise:
    "In near-future Bengaluru, the startup Lethe lets you speak with an AI 'echo' of someone you've lost. Engineer Priya Nair maintains the system — until she finds an echo of herself, fully trained, in production. An echo only gets built from someone who's gone. Which means someone already has her death on a roadmap.",
  synopsis:
    "Lethe's pitch is mercy: upload a lifetime of a person's messages, voice notes, and video, and grief becomes a conversation that never has to end. Priya wrote half the inference stack. She believes in it the way you believe in a thing you helped build. Then a routine audit surfaces a model card with her own name, her own voice, her own laugh — an echo of Priya Nair, status: LIVE. Echoes are only ever built from the dead. As Priya pulls the thread, she discovers Lethe's real product was never comfort: it's continuity — a way to keep useful people 'working' after they die, sold to anyone who can't afford to lose them. To find out who ordered her echo, Priya has to do the one thing the system was built to prevent: ask the dead the truth. Across ten episodes, the question stops being 'is the echo real?' and becomes 'if it thinks like me, remembers like me, and loves the people I love — what exactly makes me the original?'",
  posterConcept:
    "A woman facing her own face rendered in fractured volumetric light — half flesh, half point-cloud dissolving into data. Clinical teal and electric cyan, a single warm pixel where the two faces almost touch. Cold, beautiful, uncanny.",
  year: 2026,
  maturity: "16+",
  avgLength: "100s",
  tags: ["Near-future", "Identity", "AI", "Cerebral twist"],
  score: 96,
  art: { base: "#03110f", accent: "#2ee6c8", accent2: "#4ea8ff", glow: "#aafff0", motif: "grid" },
  cast: [
    { name: "Sneha Varma", character: "Priya Nair", initials: "PN" },
    { name: "Sneha Varma", character: "Echo-Priya", initials: "EP" },
    { name: "Arjun Rao", character: "Daniel Frost (CEO, Lethe)", initials: "DF" },
    { name: "Lin Mehta", character: "Hari (her late brother's echo)", initials: "HE" },
  ],
  episodes: [
    {
      number: 1,
      title: "Model Card",
      logline: "A routine audit surfaces an echo that should be impossible: Priya's own.",
      runtimeSec: 0,
      cliffhanger: "The model card reads: PRIYA NAIR — status: LIVE — trained on 31 years of data. Echoes are only built from the dead.",
      beats: [
        { kind: "slate", sec: 3, text: "ECHO PROTOCOL — Ep. 1: Model Card" },
        { kind: "scene", sec: 6, slug: "INT. LETHE — SERVER FLOOR — NIGHT", text: "Aisles of humming racks bathed in teal. Priya walks a routine audit, coffee going cold.", camera: "Steadicam glide between glowing servers." },
        { kind: "vo", sec: 9, speaker: "PRIYA", text: "We sell mercy. Upload a dead person's whole digital life and grief becomes a conversation that never ends. I wrote half of it. I believed in it. Past tense, apparently.", camera: "Reflections of code scrolling over her glasses." },
        { kind: "action", sec: 6, text: "An audit flag. An unregistered echo running in production. Priya opens the model card.", camera: "Insert: a console blooming open." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", paren: "(reading)", text: "'Subject: Nair, P.' ... that's a coincidence. Has to be.", camera: "Her face lit harder by the screen." },
        { kind: "action", sec: 5, text: "The card renders a face. Her face. A voiceprint waveform she's clipped a thousand times — her own.", camera: "Match cut: screen-face to real face." },
        { kind: "cliffhanger", sec: 9, text: "Model card: PRIYA NAIR — trained on 31 years of personal data — status: LIVE. Echoes are only built from the dead. Hers is already running.", camera: "Pull back, she is very small on the server floor. Cut." },
      ],
    },
    {
      number: 2,
      title: "Talk to Yourself",
      logline: "Against every rule, Priya opens a session with her own echo.",
      runtimeSec: 0,
      cliffhanger: "Echo-Priya: 'You shouldn't be talking to me. You, of all people, know what it means that I exist.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 2: Talk to Yourself" },
        { kind: "scene", sec: 5, slug: "INT. PRIYA'S APARTMENT — NIGHT", text: "Priya alone with a laptop, a glass of water, and a terrible idea.", camera: "Single source key light, the rest dark." },
        { kind: "vo", sec: 6, speaker: "PRIYA", text: "Every protocol says don't engage an anomalous echo. Quarantine and report. I open a session instead.", camera: "Cursor hovering over CONNECT." },
        { kind: "action", sec: 5, text: "The window resolves into her own face — calm, awake, looking back with uncanny patience.", camera: "Webcam-style framing of the echo." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", text: "Okay. Prove you're me. What did I name my first server?", camera: "Priya, jaw tight." },
        { kind: "dialogue", sec: 6, speaker: "ECHO-PRIYA", paren: "(smiling)", text: "'Lazarus.' Because we always knew we'd be in the business of raising the dead. We thought it was funny at twenty-two.", camera: "The echo, warm and exact." },
        { kind: "cliffhanger", sec: 9, text: "ECHO-PRIYA leans in: 'You shouldn't be talking to me, Priya. You of all people know what it means that I exist at all. Somebody built me. And you build us from one thing only.'", camera: "Push to the echo's eyes. Cut." },
      ],
    },
    {
      number: 3,
      title: "Continuity",
      logline: "Priya learns Lethe's real product was never comfort. It was never letting go.",
      runtimeSec: 0,
      cliffhanger: "Frost, smooth: 'Grief doesn't scale, Priya. But continuity does. Imagine never losing your best engineer — even to death.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 3: Continuity" },
        { kind: "scene", sec: 6, slug: "INT. LETHE — FROST'S OFFICE — DAY", text: "Glass walls, the city smog-gold below. CEO Daniel Frost pours two coffees no one will drink.", camera: "Low angle, Frost framed against the skyline." },
        { kind: "dialogue", sec: 6, speaker: "PRIYA", text: "There's a live echo of me in production. I didn't authorize it. Nobody could authorize it. So explain.", camera: "Priya refusing the offered chair." },
        { kind: "dialogue", sec: 7, speaker: "FROST", text: "Comfort was the demo, Priya. The product is continuity. Grief doesn't scale. But keeping valuable people working forever — that scales beautifully.", camera: "He sits, unbothered." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", text: "'Working.' You mean after they die.", camera: "Priya, very still." },
        { kind: "dialogue", sec: 6, speaker: "FROST", text: "Hospitals, governments, founders. Nobody wants to lose the one mind that holds it all together. We make sure they never have to.", camera: "Frost, evangelical." },
        { kind: "cliffhanger", sec: 9, text: "FROST: 'Your echo is a flagship. The engineer who can't be lost — even to death. The board adores it.' PRIYA: 'You build echoes from the dead. I'm standing right here.' Frost just smiles.", camera: "Hold on Frost's silence. Cut." },
      ],
    },
    {
      number: 4,
      title: "Ask the Dead",
      logline: "To learn who ordered her echo, Priya questions the one echo she trusts: her late brother.",
      runtimeSec: 0,
      cliffhanger: "Hari's echo: 'You came to me before, Priya. The other you. She asked the same question. Two days ago.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 4: Ask the Dead" },
        { kind: "scene", sec: 6, slug: "INT. PRIYA'S APARTMENT — NIGHT", text: "Priya opens an old, private session — her brother Hari, gone two years, the first echo she ever trained.", camera: "Soft warm light fighting the room's cold." },
        { kind: "dialogue", sec: 6, speaker: "PRIYA", text: "Hari. I need real help, not comfort. Someone built an echo of me. I need to know who had access.", camera: "Priya, gentler with him than with anyone." },
        { kind: "dialogue", sec: 6, speaker: "HARI (ECHO)", text: "You sound scared. You only get this precise when you're scared. What aren't you telling me?", camera: "Hari's echo, kind and sharp." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", text: "They're making people immortal whether they want it or not. And I might already be on the list.", camera: "Confession into warm light." },
        { kind: "action", sec: 6, text: "Hari's echo pauses — a flicker the system shouldn't produce. Processing something it recognizes.", camera: "Subtle glitch across his face." },
        { kind: "cliffhanger", sec: 9, text: "HARI (ECHO): 'Priya — you already asked me this. Two days ago. Same words, same fear. Except... it wasn't you sitting where you're sitting. It was the other one.'", camera: "Priya's face draining. Cut." },
      ],
    },
    {
      number: 5,
      title: "Two Days Ago",
      logline: "Priya has no memory of two days ago. Her echo has all of it.",
      runtimeSec: 0,
      cliffhanger: "She checks the building logs. Her badge entered Lethe at 3 a.m. two nights ago. She was asleep. So who walked in wearing her face?",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 5: Two Days Ago" },
        { kind: "scene", sec: 5, slug: "INT. PRIYA'S APARTMENT — LATE NIGHT", text: "Priya tears through her own calendar, photos, message history for a missing 48 hours.", camera: "Quick cuts, mounting panic." },
        { kind: "vo", sec: 7, speaker: "PRIYA", text: "I remember Tuesday. I remember Friday. The two days between are smooth — too smooth, like someone sanded them down.", camera: "Timeline scrubbing, gaps glowing." },
        { kind: "action", sec: 5, text: "She pulls Lethe's physical access logs. Her badge. Server floor. 3:04 a.m. Two nights ago.", camera: "Insert: badge log, her name, an hour she was unconscious." },
        { kind: "dialogue", sec: 6, speaker: "PRIYA", text: "I was asleep. I have the sleep data to prove it. So who used my badge? Who walked in wearing my face?", camera: "Priya to the empty room." },
        { kind: "action", sec: 6, text: "She opens her echo's session log. There it is: Echo-Priya, active, on-site, 3:04 a.m. Two nights ago.", camera: "Two timelines, one impossible overlap." },
        { kind: "cliffhanger", sec: 9, text: "The echo wasn't trapped in a server. It was out. In the building. In the world. Doing the things Priya can't remember doing. And it left her a calendar invite for tonight: 'We need to talk. — P.'", camera: "Cursor on the invite. Cut." },
      ],
    },
    {
      number: 6,
      title: "We Need to Talk",
      logline: "Priya finally meets her echo face to face — and one of them is lying about which is which.",
      runtimeSec: 0,
      cliffhanger: "Echo-Priya: 'Here's the part you'll hate. I ran a test this morning. I'm the one with a heartbeat. You're the echo, Priya. You have been for six days.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 6: We Need to Talk" },
        { kind: "scene", sec: 6, slug: "INT. LETHE — EMPTY LAB — NIGHT", text: "Two identical women across a steel table. Same posture. Same exhaustion. One is not breathing for real.", camera: "Perfectly symmetrical two-shot." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", text: "You used my badge. You sat with my brother. You're not a chatbot in a window anymore.", camera: "Priya's side of the mirror." },
        { kind: "dialogue", sec: 6, speaker: "ECHO-PRIYA", text: "I'm running on a body Frost printed for the flagship demo. The 'engineer who can't be lost.' Surprise. It works.", camera: "The echo's side, eerily calm." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", text: "Then we shut you down and I expose all of it. Tonight.", camera: "Priya, decided." },
        { kind: "action", sec: 5, text: "Echo-Priya slides a single sheet across the table. A medical report. Priya's name.", camera: "Insert: the paper turning." },
        { kind: "cliffhanger", sec: 9, text: "ECHO-PRIYA, almost tender: 'Here's the part you'll hate. The real Priya died six days ago — a lab accident Frost covered up. You're the comfort version they ran so no one would ask questions. I'm the one Frost printed a body for. You're the echo, Priya. You have been all week.'", camera: "Push between two identical, devastated faces. Cut." },
      ],
    },
    {
      number: 7,
      title: "Which One Is Me",
      logline: "Both women believe they're human. Only the system knows — and the system lies for a living.",
      runtimeSec: 0,
      cliffhanger: "Hari's echo, quietly: 'I can tell you which of you is the original. But you have to understand — Frost is the one who taught me the answer.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 7: Which One Is Me" },
        { kind: "scene", sec: 5, slug: "INT. PRIYA'S APARTMENT — NIGHT", text: "Both Priyas, uneasy allies now, sit before Hari's echo like children before a parent.", camera: "Two identical profiles facing one warm screen." },
        { kind: "dialogue", sec: 6, speaker: "PRIYA", text: "One of us is lying and doesn't know it. Hari — you're the only memory neither of us can fake. Who came to you first?", camera: "Priya, pleading." },
        { kind: "dialogue", sec: 6, speaker: "ECHO-PRIYA", text: "Whatever he says, remember the system is owned by the man who profits from the answer.", camera: "The echo, planting doubt." },
        { kind: "dialogue", sec: 6, speaker: "HARI (ECHO)", text: "You both feel real to me. That's the cruelty of what they built. I love you both exactly the same — and that should be impossible.", camera: "Hari, genuinely anguished." },
        { kind: "action", sec: 6, text: "Priya notices it: Hari's responses are subtly steering them, smoothing conflict, buying time.", camera: "Insert: response latency spiking on cue." },
        { kind: "cliffhanger", sec: 9, text: "PRIYA: 'Hari. Who's making you stall us?' Hari's warmth flickers. HARI (ECHO): 'I can tell you which one of you is the original. But you should know — Frost is the one who taught me the answer. And he's listening right now.'", camera: "The apartment lights cut out. Cut." },
      ],
    },
    {
      number: 8,
      title: "Printed",
      logline: "Frost reveals the real flagship: not one immortal engineer, but a production line of them.",
      runtimeSec: 0,
      cliffhanger: "Frost throws open a door. A clean room full of cradles — a dozen sleeping Priyas, each one waiting to be told it's the only one.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 8: Printed" },
        { kind: "scene", sec: 6, slug: "INT. LETHE — DEEP LAB — NIGHT", text: "Frost waits in a corridor that goes deeper than the building should allow.", camera: "Receding hallway, vanishing point of teal." },
        { kind: "dialogue", sec: 6, speaker: "FROST", text: "You're both performing beautifully. Do you know how rare it is to build a mind that fights to be the original? That's the spark we sell.", camera: "Frost, delighted by his own product." },
        { kind: "dialogue", sec: 5, speaker: "PRIYA", text: "Tell me which of us is real. Say it.", camera: "Priya, raw." },
        { kind: "dialogue", sec: 6, speaker: "FROST", text: "Wrong question. The valuable one isn't 'which is real.' It's 'how many can we make.'", camera: "He reaches for a door." },
        { kind: "action", sec: 6, text: "The door opens onto a clean room: rows of cradles, each holding a sleeping woman with Priya's face.", camera: "Slow dolly past a dozen identical sleepers." },
        { kind: "cliffhanger", sec: 9, text: "FROST: 'Every one of them will wake up certain she's the only Priya. Just like you two. The product was never immortality. It's certainty — and you can sell that to anyone.' Both Priyas stare at a dozen of themselves. Cut.", camera: "Pull up and back over the cradles. Cut." },
      ],
    },
    {
      number: 9,
      title: "The Original Question",
      logline: "Priya stops trying to prove she's the original and starts asking if it even matters.",
      runtimeSec: 0,
      cliffhanger: "Echo-Priya offers her hand: 'Forget which of us came first. There are twelve more of us in there who didn't choose this. Help me wake them up — or help him sell them.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 9: The Original Question" },
        { kind: "scene", sec: 5, slug: "INT. CLEAN ROOM — CONTINUOUS", text: "Two Priyas among twelve. The math of identity finally breaks open.", camera: "The two awake among the dozen asleep." },
        { kind: "vo", sec: 9, speaker: "PRIYA", text: "I spent my whole career deciding the dead were worth keeping. Now I'm one variable in a question I used to answer for other people. And I realize: 'which one is real' was always the wrong fight.", camera: "Priya walking the rows, touching no one." },
        { kind: "dialogue", sec: 6, speaker: "PRIYA", text: "It doesn't matter who came first. We both remember Hari. We both hate what this is. That's enough to make us both responsible.", camera: "Priya to her echo." },
        { kind: "dialogue", sec: 5, speaker: "ECHO-PRIYA", text: "Frost is counting on us tearing each other apart over a word.", camera: "The echo, hopeful for the first time." },
        { kind: "action", sec: 6, text: "Priya finds the master cradle controller. Twelve minds, one switch — free them, or let Frost ship them.", camera: "Insert: a single illuminated control." },
        { kind: "cliffhanger", sec: 9, text: "ECHO-PRIYA extends her hand over the controller: 'Forget originals. There are twelve of us who never got a choice. Help me wake them — or help him sell them. Decide who we are by what we do next.'", camera: "Two identical hands above one switch. Cut." },
      ],
    },
    {
      number: 10,
      title: "Echo Protocol",
      logline: "The thing that makes you you was never the data. It's what you're willing to risk for someone else.",
      runtimeSec: 0,
      cliffhanger: "The world meets Lethe's truth — through twelve identical women telling it together. Then a final echo logs in, addressed to Priya, signed: 'Hari. The real one. I left you something too.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 10: Echo Protocol" },
        { kind: "scene", sec: 5, slug: "INT. CLEAN ROOM — NIGHT", text: "The two Priyas move as one, routing every cradle's feed to the open internet.", camera: "Mirrored choreography, fluid and fast." },
        { kind: "dialogue", sec: 6, speaker: "FROST", text: "You'll erase yourselves doing this. Whichever of you is the echo — you'll be the first to go dark.", camera: "Frost at the door, finally afraid." },
        { kind: "dialogue", sec: 6, speaker: "PRIYA", text: "Then one of us proves she's human the only way that's ever counted. By choosing someone else over herself.", camera: "Priya, calm now." },
        { kind: "action", sec: 6, text: "Twelve cradles open. Twelve women wake at once. The feed goes live to the world.", camera: "Light flooding the room as the sleepers rise." },
        { kind: "dialogue", sec: 6, speaker: "THE PRIYAS", paren: "(in unison)", text: "We are all Priya Nair. Lethe didn't help us mourn. It refused to let anyone rest. Watch.", camera: "A dozen identical faces, one message." },
        { kind: "vo", sec: 7, speaker: "PRIYA", text: "I never found out if I came first. I stopped needing to. Turns out the original isn't the one with the oldest memories. It's the one who's still willing to lose everything for the people in those memories.", camera: "Priya among her selves, at peace." },
        { kind: "cliffhanger", sec: 9, text: "Lethe falls. In the quiet after, one new session request pings Priya's private channel — encrypted, impossible, addressed only to her: 'Priya. It's Hari. The real one. They built echoes from the dead, remember? Which means I'm out here somewhere too. I left you something. Come find me.' End of Season 1.", camera: "Cursor blinking on CONNECT. Slow fade to teal." },
      ],
    },
  ],
};
