import type { Series } from "../types";

// CRIME — A daughter returns for a funeral and inherits a town's secret.
export const saltwater: Series = {
  id: "s-saltwater",
  slug: "saltwater",
  title: "Saltwater",
  genre: "Crime",
  tagline: "She came home to bury her father. The whole town came to make sure she left.",
  premise:
    "Marisha returns to the Goan fishing village she fled at eighteen to bury the father she never forgave. His trawler, the Mae do Mar, was the pride of the harbour. It was also the quiet engine of a smuggling route every family in town depends on — and now that the captain's daughter is back, everyone needs to know whose side she's on.",
  synopsis:
    "Velha Aldeia is postcard-perfect: whitewashed chapels, blue boats, the smell of drying fish and frangipani. Marisha left it at eighteen and never looked back. She returns a stranger in her own black dress, only to find the funeral half-empty and the harbour watching her like weather. Her father didn't just fish. For thirty years the Mae do Mar ran something else past the coast guard — and the money built every roof in the village. With the captain gone, the route is leaderless, the buyers are nervous, and the one person who could inherit it all is the daughter who hates it most. As Marisha digs, the warm town turns cold: a kindly priest, an old flame turned constable, an aunt with too many keys. Everyone loved her father. Everyone is also a suspect. Across ten episodes she learns the truth doesn't set you free in Velha Aldeia — it just decides which tide takes you out.",
  posterConcept:
    "A lone blue fishing trawler at golden hour, beautiful and ominous, its long shadow falling across a beach toward a single woman in funeral black. Sun-bleached noir: warm amber sky, deep teal water, sand the colour of old bone.",
  year: 2026,
  maturity: "16+",
  avgLength: "95s",
  tags: ["Small-town noir", "Coastal", "Slow-burn", "Family secret"],
  score: 92,
  art: { base: "#0c0f10", accent: "#e0a44a", accent2: "#2f8a8a", glow: "#ffe2a8", motif: "tide" },
  cast: [
    { name: "Joana Fernandes", character: "Marisha Pereira", initials: "MP" },
    { name: "Caetano Dias", character: "Const. Elias Costa", initials: "EC" },
    { name: "Branca Rebelo", character: "Tia Lurdes", initials: "TL" },
    { name: "Father figure", character: "Padre Anselmo", initials: "PA" },
  ],
  episodes: [
    {
      number: 1,
      title: "The Half-Empty Funeral",
      logline: "Marisha buries a father she didn't forgive, in a town that won't meet her eyes.",
      runtimeSec: 0,
      cliffhanger: "An old fisherman presses something into her palm at the grave: the trawler's key, and a whisper — 'Don't take her out. Whatever they tell you, don't take the Mae do Mar out.'",
      beats: [
        { kind: "slate", sec: 3, text: "SALTWATER — Ep. 1: The Half-Empty Funeral" },
        { kind: "scene", sec: 6, slug: "EXT. HILLSIDE CEMETERY — DAY", text: "A whitewashed chapel above a glittering bay. A coffin, a priest, and far too few mourners.", camera: "High wide: the small crowd dwarfed by sea and sky." },
        { kind: "vo", sec: 9, speaker: "MARISHA", text: "I left at eighteen and swore I'd only come back for this. Half the town owes my father everything. So why does it feel like they're here to watch me, not him?", camera: "Slow push on her face behind dark glasses." },
        { kind: "action", sec: 5, text: "Across the grave, a constable watches her instead of the coffin. An old flame. Elias.", camera: "Rack focus from coffin to Elias." },
        { kind: "dialogue", sec: 5, speaker: "PADRE ANSELMO", text: "He was a good captain, Marisha. The sea gives, the sea takes. Let it rest now.", camera: "The priest, too smooth, too quick." },
        { kind: "action", sec: 5, text: "An ancient fisherman, hands like rope, grips hers as the crowd thins.", camera: "Macro: weathered hand closing over hers." },
        { kind: "cliffhanger", sec: 9, text: "He presses a worn brass key into her palm. 'The Mae do Mar is yours now, child. But hear me — don't take her out. Whatever they tell you, whatever they offer. Don't take that boat out.' Then he's gone into the crowd.", camera: "Marisha alone with the key. Cut." },
      ],
    },
    {
      number: 2,
      title: "The Pride of the Harbour",
      logline: "Marisha boards her father's trawler and finds it's worth more than any catch.",
      runtimeSec: 0,
      cliffhanger: "Below deck, behind the ice hold, a false floor. Beneath it: vacuum-sealed packages and a ledger with thirty years of names — half the village among them.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 2: The Pride of the Harbour" },
        { kind: "scene", sec: 6, slug: "EXT. HARBOUR — DUSK", text: "Blue boats nodding on amber water. The Mae do Mar sits apart, bigger, better kept than a fisherman could afford.", camera: "Golden-hour glide along the hulls." },
        { kind: "vo", sec: 7, speaker: "MARISHA", text: "A trawler like this costs more than this whole village makes in a year. He always said the sea was generous. He never said with what.", camera: "Marisha's hand on the worn rail." },
        { kind: "action", sec: 6, text: "She unlocks the cabin. Charts, a radio too new for the boat, a coil of foreign banknotes in a coffee tin.", camera: "Insert tour: details that don't add up." },
        { kind: "action", sec: 6, text: "In the ice hold, the floor rings hollow under her heel. She pries up a board.", camera: "Low angle as the false floor lifts." },
        { kind: "action", sec: 5, text: "Vacuum-sealed packages, neat as bricks. And under them, a battered ledger.", camera: "The hold light swinging." },
        { kind: "cliffhanger", sec: 9, text: "She opens the ledger. Thirty years of dates, weights, payments — and names. The priest. Her aunt. The grocer. Elias's father. Half of Velha Aldeia, written in her father's hand.", camera: "Finger tracing down familiar names. Cut." },
      ],
    },
    {
      number: 3,
      title: "Everyone Knew",
      logline: "Marisha realizes the town's warmth was always a fence, and she's now inside it.",
      runtimeSec: 0,
      cliffhanger: "Tia Lurdes sets down the tea: 'Your father carried this village for thirty years, querida. Now you'll carry it. There was never another ending.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 3: Everyone Knew" },
        { kind: "scene", sec: 6, slug: "INT. TIA LURDES'S KITCHEN — NIGHT", text: "Warm lamplight, the smell of fish curry, an aunt who raised her pouring tea like nothing's wrong.", camera: "Cozy warm tones turning faintly sinister." },
        { kind: "dialogue", sec: 6, speaker: "MARISHA", text: "Your name's in his book, Tia. Dates. Money. You knew. All of you knew.", camera: "Marisha across the small table." },
        { kind: "dialogue", sec: 7, speaker: "TIA LURDES", paren: "(unbothered)", text: "Knew? Child, we built it. Who do you think roofed the school? Paid for old Rosa's surgery? The sea didn't. Your father did. Quietly.", camera: "Lurdes stirring sugar, calm as Sunday." },
        { kind: "dialogue", sec: 5, speaker: "MARISHA", text: "It's smuggling. People go to prison for that ledger.", camera: "Marisha gripping the cup." },
        { kind: "dialogue", sec: 6, speaker: "TIA LURDES", text: "People also eat. People also keep their boats. Don't bring city words into a fishing town.", camera: "A flash of steel under the warmth." },
        { kind: "cliffhanger", sec: 9, text: "Lurdes pats her hand. 'He carried this village for thirty years, querida. Now you carry it. The route needs a captain who owns the Mae do Mar. That's you. There was never going to be another ending.'", camera: "Marisha's face in the warm, trapping light. Cut." },
      ],
    },
    {
      number: 4,
      title: "Old Flame, New Badge",
      logline: "Constable Elias offers protection. Marisha can't tell if it's love, law, or a leash.",
      runtimeSec: 0,
      cliffhanger: "Elias: 'I'm the only thing standing between you and a coast guard raid.' Marisha: 'Or you're the one who'll call it in if I say no.' His silence answers.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 4: Old Flame, New Badge" },
        { kind: "scene", sec: 6, slug: "EXT. SEAWALL — NIGHT", text: "Waves slapping stone. Two people who used to be teenagers here, now wary adults.", camera: "Two-shot against black water and distant boat lights." },
        { kind: "dialogue", sec: 6, speaker: "ELIAS", text: "You should've stayed gone, Mari. I mean that kindly. This town doesn't let go of what it needs.", camera: "Elias, hands in pockets, badge catching moonlight." },
        { kind: "dialogue", sec: 5, speaker: "MARISHA", text: "You're police. You could end this with one report.", camera: "Marisha testing him." },
        { kind: "dialogue", sec: 7, speaker: "ELIAS", text: "My father's in that ledger. My pension's in this town. I'm the only thing between you and a coast guard raid that takes everyone down — including you.", camera: "Closer, lower, intimate and threatening at once." },
        { kind: "action", sec: 5, text: "An old tenderness flickers between them. Both pretend not to see it.", camera: "Insert: her hand near his, not quite touching." },
        { kind: "cliffhanger", sec: 9, text: "MARISHA: 'Protection. Or a leash?' ELIAS says nothing. The wave that hits the wall is the only answer she gets. She understands it perfectly.", camera: "Spray over the seawall. Cut." },
      ],
    },
    {
      number: 5,
      title: "The Buyer",
      logline: "With the captain dead, the people on the other end of the route come ashore to inspect their new partner.",
      runtimeSec: 0,
      cliffhanger: "The buyer studies her, then smiles: 'Your father skimmed us for two years. We let it go out of respect. You start clean — by repaying what he stole. One run. Or we settle it the old way.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 5: The Buyer" },
        { kind: "scene", sec: 6, slug: "INT. BEACH SHACK — NIGHT", text: "After hours. Chairs stacked, one table down, two men who don't belong to this coast.", camera: "Low key, a single bulb swinging." },
        { kind: "vo", sec: 6, speaker: "MARISHA", text: "The village were the hands. These are the people the hands work for. They came to look at the new captain. To see if I'd kneel.", camera: "Marisha entering, spine straight." },
        { kind: "dialogue", sec: 6, speaker: "THE BUYER", text: "Captain Pereira's girl. He spoke of you. Said you ran to the city so you'd never have to do this.", camera: "The buyer, soft-voiced, terrifying." },
        { kind: "dialogue", sec: 5, speaker: "MARISHA", text: "He was right. I'm here to bury him and sell the boat. That's all.", camera: "Marisha holding her ground." },
        { kind: "action", sec: 5, text: "The buyer slides a number across the table. A debt. Her father's name beside it.", camera: "Insert: a figure that owns a person." },
        { kind: "cliffhanger", sec: 9, text: "THE BUYER: 'Your father skimmed us two years. We allowed it — out of respect. You inherit the boat and the debt. Run it once. Repay what he stole. Then walk, if you still want to.' He pauses. 'Or we settle the old way. The sea is patient.'", camera: "Push on Marisha doing the math of her own survival. Cut." },
      ],
    },
    {
      number: 6,
      title: "The Old Way",
      logline: "Marisha learns her father may not have drowned by accident — and that the ledger is leverage.",
      runtimeSec: 0,
      cliffhanger: "The harbour-master, drunk and afraid: 'Your father wanted out. Told the buyer he was done. Three days later the sea took him. You really think that's a coincidence, captain?'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 6: The Old Way" },
        { kind: "scene", sec: 6, slug: "INT. HARBOUR TAVERN — NIGHT", text: "Feni and fear. The old harbour-master won't look at her but won't stop talking.", camera: "Smoky warm interior, faces half in shadow." },
        { kind: "dialogue", sec: 6, speaker: "MARISHA", text: "They keep saying the sea took him. He sailed these waters fifty years. He didn't just fall.", camera: "Marisha leaning across the bar." },
        { kind: "dialogue", sec: 7, speaker: "HARBOUR-MASTER", paren: "(drunk, low)", text: "He'd had enough. Said the city had made his daughter clean, and he wanted to be clean too. Told the buyer: no more runs.", camera: "The old man into his glass." },
        { kind: "dialogue", sec: 5, speaker: "MARISHA", text: "And?", camera: "Marisha very still." },
        { kind: "action", sec: 5, text: "The harbour-master finally meets her eyes. Pure dread.", camera: "Insert: bloodshot eyes lifting." },
        { kind: "cliffhanger", sec: 9, text: "HARBOUR-MASTER: 'Three days later the sea took him. A man who could read this coast blind. You think that's an accident, captain?' He drains the glass. 'You want out too? You'll go out the same way. Unless that ledger of yours is worth more to them alive.'", camera: "Marisha realizing the book is a weapon. Cut." },
      ],
    },
    {
      number: 7,
      title: "Leverage",
      logline: "Marisha stops running and starts negotiating — using the one thing that can sink everyone.",
      runtimeSec: 0,
      cliffhanger: "She tells the buyer copies of the ledger sit with a lawyer in the city, set to release if she dies or disappears. The buyer's smile vanishes: 'Your father said the exact same thing. Word for word.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 7: Leverage" },
        { kind: "scene", sec: 5, slug: "EXT. JETTY — DAWN", text: "Grey light. Marisha waits for the buyer on her own terms, the ledger nowhere in sight.", camera: "Cold dawn palette, the warm town drained of colour." },
        { kind: "vo", sec: 6, speaker: "MARISHA", text: "I spent fifteen years learning the city doesn't fight with fists. It fights with paper. And I'm holding thirty years of the wrong people's paper.", camera: "Marisha steady, transformed." },
        { kind: "dialogue", sec: 6, speaker: "MARISHA", text: "Copies of the ledger are with a lawyer in the city. If I drown, if I vanish, if I so much as slip on your jetty — it all goes public. Names. Dates. You.", camera: "Marisha to the buyer, unflinching." },
        { kind: "action", sec: 5, text: "The buyer studies her for a long, cold moment. Recalculating.", camera: "Insert: his jaw tightening." },
        { kind: "dialogue", sec: 5, speaker: "THE BUYER", text: "Clever. The city did make you clean. And sharp.", camera: "A thin, dangerous smile." },
        { kind: "cliffhanger", sec: 9, text: "Then his smile dies. THE BUYER: 'You should know — your father stood on this exact jetty and said the exact same words. Lawyer in the city. Release if he died. Word for word.' A beat. 'We never found that lawyer. We never found those copies. Do you see your problem?'", camera: "Marisha's bluff turning to ice. Cut." },
      ],
    },
    {
      number: 8,
      title: "What He Left Her",
      logline: "Marisha discovers her father did leave a fail-safe — hidden in the only language they still shared.",
      runtimeSec: 0,
      cliffhanger: "The charts aren't fishing routes. Plotted across two years of 'catches' is a map — to where her father hid everything he ever skimmed, and the evidence to bury the buyer with it.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 8: What He Left Her" },
        { kind: "scene", sec: 6, slug: "INT. MAE DO MAR CABIN — NIGHT", text: "Marisha tears the cabin apart for what her father hid better than a lawyer could.", camera: "Tight, frantic handheld in the swaying cabin." },
        { kind: "vo", sec: 7, speaker: "MARISHA", text: "We never agreed on anything. Except the sea. He taught me to read charts before I could read words. If he hid something from everyone — he hid it where only I could read it.", camera: "Her hands moving over old paper charts." },
        { kind: "action", sec: 6, text: "The fishing charts. Marks for 'good catches,' two years of them. Useless — unless you connect them.", camera: "Insert: dots across laminated charts." },
        { kind: "action", sec: 6, text: "She joins the marks in date order. They aren't catches. They're a path, ending at a single cove.", camera: "Lines resolving into a map." },
        { kind: "dialogue", sec: 5, speaker: "MARISHA", paren: "(breath catching)", text: "You didn't skim for the money. You skimmed for proof.", camera: "Realization lighting her face." },
        { kind: "cliffhanger", sec: 9, text: "X marks a sea cave only reachable at low tide. Pencilled beside it in her father's hand: 'For my Mari. Everything they did. Everything I did. Burn it or use it. Forgive me either way.'", camera: "Macro on his handwriting. Cut." },
      ],
    },
    {
      number: 9,
      title: "Low Tide",
      logline: "To reach her father's evidence, Marisha must take the one boat she was warned never to sail.",
      runtimeSec: 0,
      cliffhanger: "Inside the cave: years of evidence, and stacks of cash. And waiting in the dark, lantern lit, already there — Elias. 'I hoped you wouldn't find it, Mari. Now I have to choose. And so do you.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 9: Low Tide" },
        { kind: "scene", sec: 6, slug: "EXT. OPEN SEA — PRE-DAWN", text: "Marisha takes the Mae do Mar out alone, against the old man's only warning.", camera: "Small boat, vast dark water, one running light." },
        { kind: "vo", sec: 6, speaker: "MARISHA", text: "'Don't take the boat out.' Maybe he meant the route would claim me. Maybe he meant I'd become the captain. Tonight I find out which.", camera: "Marisha at the wheel, jaw set." },
        { kind: "action", sec: 6, text: "She noses into a black sea cave as the tide bottoms out, hull scraping stone.", camera: "The cave mouth swallowing the boat." },
        { kind: "action", sec: 6, text: "Her lantern finds them: waterproof crates, two years of evidence, and bricks of cash gone soft with damp.", camera: "Light sweeping across the hoard." },
        { kind: "sfx", sec: 4, text: "A second lantern flares to life deeper in the cave. Someone is already here." },
        { kind: "cliffhanger", sec: 9, text: "Elias steps from the dark, lantern raised, gun lowered but present. 'I hoped you wouldn't find it. I really did.' He looks at the crates, then at her. 'Your father trusted me to make sure no one ever did. Now I have to choose what kind of man I am. And you have to choose if you trust the boy I was over the badge I wear.'", camera: "Two lanterns, two faces, one impossible choice. Cut." },
      ],
    },
    {
      number: 10,
      title: "Saltwater",
      logline: "Marisha decides what to do with a town's secret — and what kind of captain she'll be.",
      runtimeSec: 0,
      cliffhanger: "The buyer falls; the village holds its breath. Months later, a clean Mae do Mar runs a real catch — but a new coil of foreign notes turns up in Marisha's net, with a note: 'A town has to eat. Welcome back, Captain.' She looks at the horizon. She doesn't throw it overboard.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 10: Saltwater" },
        { kind: "scene", sec: 6, slug: "INT. SEA CAVE — CONTINUOUS", text: "Two people, one hoard, and a choice that decides a hundred lives.", camera: "Claustrophobic, lantern-lit, water rising." },
        { kind: "dialogue", sec: 6, speaker: "ELIAS", text: "Give it to the coast guard and you sink everyone. Tia Lurdes. The grocer. Me. The whole village that raised you.", camera: "Elias, pleading, human." },
        { kind: "dialogue", sec: 6, speaker: "MARISHA", text: "Or I keep it. And I become exactly what he was. The captain who carries the secret so no one else has to.", camera: "Marisha weighing the crates and the cash." },
        { kind: "action", sec: 6, text: "She chooses a third way: the evidence on the buyer goes out — only the buyer. The village's names, she burns.", camera: "Papers feeding a small bright fire." },
        { kind: "vo", sec: 8, speaker: "MARISHA", text: "I gave them the man at the top. I let the village keep its roofs and its lie. I told myself it was mercy. The sea knows it was something closer to surrender.", camera: "Firelight on her unreadable face." },
        { kind: "action", sec: 6, text: "MONTHS LATER. The Mae do Mar, repainted, hauls an honest catch in clean morning light.", camera: "Bright, warm, almost a different show — almost." },
        { kind: "cliffhanger", sec: 9, text: "Marisha pulls the net — and among the fish, a coil of foreign banknotes, dry, deliberate, with a folded note: 'A town has to eat. Welcome home, Captain.' She scans the empty horizon. Her hand closes around the money. She does not throw it back. End of Season 1.", camera: "Slow pull up and away from the lone boat on the glittering sea. Fade." },
      ],
    },
  ],
};
