import type { Series } from "../types";

// THRILLER — A woman receives texts from her dead sister's phone.
export const theLastMessage: Series = {
  id: "s-last-message",
  slug: "the-last-message",
  title: "The Last Message",
  genre: "Thriller",
  tagline: "She buried her sister three days ago. Her sister just texted back.",
  premise:
    "Maya, a Mumbai sound editor, receives a text from her sister Anjali's phone — three days after Anjali's funeral. Each new message drags Maya deeper into a death that was never real, and a truth someone is willing to kill to keep buried.",
  synopsis:
    "When Anjali drowns off the Worli sea face, the case is closed in a single afternoon: an accident, a strong current, a body the sea kept. Maya signs the papers and tries to disappear into her edit suite. Then her phone lights up with a name that should be gone. The messages are precise, private, impossible — they know things only Anjali knew. As Maya follows the thread through a city that suddenly feels staged, she learns her sister spent her last months investigating the very people now watching Maya. Ten episodes, one tightening noose: is Anjali alive and hiding, or is someone wearing her like a mask to finish what she started?",
  posterConcept:
    "A phone screen glowing in a dark, rain-streaked room; the reflection on the wet glass is a woman's face that is not quite the owner's. Cold cyan light, deep ink-black negative space, a single unread message bubble as the only warm element.",
  year: 2026,
  maturity: "16+",
  avgLength: "95s",
  tags: ["Slow-burn", "Mystery", "Mumbai noir", "Twist ending"],
  score: 94,
  art: { base: "#070a12", accent: "#23d3ee", accent2: "#3b5bdb", glow: "#9bf6ff", motif: "signal" },
  cast: [
    { name: "Tara Sequeira", character: "Maya Rao", initials: "MR" },
    { name: "Nikhita Bose", character: "Anjali Rao", initials: "AR" },
    { name: "Imran Qureshi", character: "Insp. Vikram Salvi", initials: "VS" },
    { name: "Devika Menon", character: "Rehana ('the contact')", initials: "RC" },
  ],
  episodes: [
    {
      number: 1,
      title: "Read Receipt",
      logline: "Three days after the funeral, the dead start typing.",
      runtimeSec: 0,
      cliffhanger: "The typing bubble appears. Then: 'You used the wrong photo at the funeral.'",
      beats: [
        { kind: "slate", sec: 3, text: "THE LAST MESSAGE — Ep. 1: Read Receipt" },
        { kind: "scene", sec: 6, slug: "INT. MAYA'S EDIT SUITE — NIGHT", text: "A dark room lit only by waveforms. Maya scrubs the same two seconds of audio over and over.", camera: "Slow push on her face, screens reflected in her eyes." },
        { kind: "vo", sec: 9, speaker: "MAYA", text: "They closed the file in an afternoon. Strong current, they said. The sea keeps what it takes. I signed where they pointed.", camera: "Macro on a pen hovering over a death certificate." },
        { kind: "sfx", sec: 3, text: "A phone buzzes against the desk — too loud in the silence." },
        { kind: "action", sec: 7, text: "The screen glows. A name surfaces that should not exist anymore: ANJALI.", camera: "Insert: the notification, harsh cyan, the room falling away behind it." },
        { kind: "dialogue", sec: 8, speaker: "MAYA", paren: "(barely breathing)", text: "Who is this. This isn't funny. Whoever you are, this isn't funny.", camera: "Handheld, breath fogging the cold glass." },
        { kind: "cliffhanger", sec: 9, text: "Three dots. Typing. Then: 'You used the wrong photo at the funeral. I hated that one.'", camera: "Hard cut to black on the buzz." },
      ],
    },
    {
      number: 2,
      title: "Proof of Life",
      logline: "Maya demands proof. The phone answers with a secret only two people knew.",
      runtimeSec: 0,
      cliffhanger: "A photo arrives — Maya's own front door, taken from across the street, timestamped four minutes ago.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 2: Proof of Life" },
        { kind: "scene", sec: 6, slug: "INT. MAYA'S FLAT — NIGHT", text: "Maya paces with the phone like it's a live wire.", camera: "Orbiting handheld, never quite still." },
        { kind: "dialogue", sec: 7, speaker: "MAYA", text: "If you're really her — the word. The one only we used. What did we call the building terrace?", camera: "Tight on her thumb, hovering." },
        { kind: "action", sec: 5, text: "Three dots. A long pause that lasts a year.", camera: "Clock on the wall, second hand loud." },
        { kind: "dialogue", sec: 6, speaker: "ANJALI (TEXT)", text: "'The Almost-Sky.' Because we never quite reached it. Hello, Maya.", camera: "The message blooms on screen." },
        { kind: "vo", sec: 8, speaker: "MAYA", text: "Nobody knew that. Not Mum. Not the police. Not the man I almost married. Nobody.", camera: "Her reflection multiplied in the dark window." },
        { kind: "cliffhanger", sec: 9, text: "Another image loads: her own front door, shot from across the street. Timestamp: four minutes ago.", camera: "Slow zoom into the photo until the grain swallows the frame." },
      ],
    },
    {
      number: 3,
      title: "The Wrong Funeral",
      logline: "Maya reopens the casket question and learns what the sea did — and didn't — return.",
      runtimeSec: 0,
      cliffhanger: "The morgue clerk goes pale: 'Ma'am — that body was claimed and cremated by someone. It wasn't you.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 3: The Wrong Funeral" },
        { kind: "scene", sec: 6, slug: "INT. CIVIC MORGUE — DAY", text: "Fluorescent hum. A clerk slides a ledger across cold steel.", camera: "Overhead, the two of them small under the lights." },
        { kind: "dialogue", sec: 7, speaker: "MAYA", text: "My sister. Anjali Rao. I need to see the identification record. Who confirmed it was her.", camera: "Eyeline match across the counter." },
        { kind: "action", sec: 6, text: "The clerk frowns, flips pages, flips them back.", camera: "Insert: a signature that isn't Maya's, in a name she doesn't know." },
        { kind: "dialogue", sec: 6, speaker: "CLERK", paren: "(uneasy)", text: "You signed the cremation order. See? Right here.", camera: "Finger on the line." },
        { kind: "dialogue", sec: 7, speaker: "MAYA", paren: "(quiet, cold)", text: "I never came here. I was given an urn. I never saw a body.", camera: "Push in as the floor tilts under her." },
        { kind: "cliffhanger", sec: 9, text: "The clerk reads the file twice and pales: 'Ma'am — this body was claimed and cremated by someone. The signature isn't yours. So who burned your sister?'", camera: "Snap to black." },
      ],
    },
    {
      number: 4,
      title: "Rehana",
      logline: "A stranger leaves a note in Maya's coat: 'Anjali sent me. Stop texting back.'",
      runtimeSec: 0,
      cliffhanger: "Rehana grabs Maya's wrist: 'The phone you're talking to is in this room. Don't turn around.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 4: Rehana" },
        { kind: "scene", sec: 6, slug: "INT. IRANI CAFÉ — DAY", text: "Steam, chipped marble tables, ceiling fans. A woman in grey watches Maya from the corner.", camera: "Rack focus from teacup to the watcher." },
        { kind: "action", sec: 5, text: "Maya finds a folded note in her coat pocket she didn't put there.", camera: "Insert: 'Anjali sent me. Stop texting back. — R'" },
        { kind: "dialogue", sec: 7, speaker: "REHANA", paren: "(sitting down uninvited)", text: "Your sister wasn't a sound editor's quiet sister. She was building a case. Against people who don't lose.", camera: "Two-shot, low and close." },
        { kind: "dialogue", sec: 6, speaker: "MAYA", text: "What people? Building what case? She fixed audio for ad films.", camera: "Maya leaning in despite herself." },
        { kind: "dialogue", sec: 7, speaker: "REHANA", text: "She fixed audio for a lot of rooms that thought they were private. Then one of those rooms found out.", camera: "Rehana's eyes flick to the door." },
        { kind: "cliffhanger", sec: 9, text: "Rehana grips Maya's wrist, voice flat: 'The phone you've been texting is in this café, right now. Don't turn around.'", camera: "The fan blades stutter across the frame. Cut." },
      ],
    },
    {
      number: 5,
      title: "The Recording",
      logline: "Anjali's last project was never an ad. It was a confession someone paid to silence.",
      runtimeSec: 0,
      cliffhanger: "Maya hits play and hears her sister's voice — and her own name, spoken as a warning.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 5: The Recording" },
        { kind: "scene", sec: 6, slug: "INT. MAYA'S EDIT SUITE — NIGHT", text: "Rehana hands Maya a battered drive. Maya's hands know this work even when her heart doesn't.", camera: "Macro on the drive sliding home." },
        { kind: "vo", sec: 7, speaker: "MAYA", text: "I've cleaned ten thousand recordings. I can pull a whisper out of a hurricane. Anjali knew that. Of course she left it for me.", camera: "Waveform unspools across the screen." },
        { kind: "action", sec: 6, text: "Under static, a man's voice surfaces — measured, powerful, discussing a 'liability' that needs to 'go quiet.'", camera: "EQ bands lighting up like a heartbeat." },
        { kind: "dialogue", sec: 6, speaker: "REHANA", text: "That's the man your sister was about to hand to a journalist. The morning she 'drowned.'", camera: "Rehana lit only by the monitor." },
        { kind: "action", sec: 6, text: "Maya isolates one more layer. A second voice, fainter. Female. Recording in secret.", camera: "Slow zoom on a single trembling waveform." },
        { kind: "cliffhanger", sec: 9, text: "The hidden voice is Anjali's: 'If you're hearing this, Maya, I'm already gone — and they'll come for you next. Trust the phone. Don't trust Rehana.'", camera: "Maya turns to Rehana. Black." },
      ],
    },
    {
      number: 6,
      title: "Don't Trust Rehana",
      logline: "Two people claim to speak for the dead. Only one of them is lying.",
      runtimeSec: 0,
      cliffhanger: "Rehana's photo ID, dropped in the struggle, names her as a private contractor — hired by the man on the tape.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 6: Don't Trust Rehana" },
        { kind: "scene", sec: 6, slug: "INT. EDIT SUITE — CONTINUOUS", text: "The room shrinks to two women and one truth too many.", camera: "Whip-pan between their faces." },
        { kind: "dialogue", sec: 6, speaker: "MAYA", text: "She says don't trust you. Why would my sister warn me about the person who 'protects' me?", camera: "Maya backing toward the door." },
        { kind: "dialogue", sec: 7, speaker: "REHANA", paren: "(too calm)", text: "Because the phone isn't your sister, Maya. It's the only thing left of her that they control.", camera: "Rehana stepping closer with each word." },
        { kind: "action", sec: 6, text: "Maya throws the studio into darkness — kills the lights, the one advantage of her own room.", camera: "Total black, then strobing monitor light." },
        { kind: "action", sec: 6, text: "A scuffle. A bag spills. A laminated card skids under the desk.", camera: "Insert under the desk: an ID catching the strobe." },
        { kind: "cliffhanger", sec: 9, text: "The card: Rehana, security contractor — for the company owned by the man on the tape. Above, Maya's phone lights up: 'Run. Now.'", camera: "Cut on the glow." },
      ],
    },
    {
      number: 7,
      title: "The Man on the Tape",
      logline: "Maya stops running from the voice and starts hunting it.",
      runtimeSec: 0,
      cliffhanger: "The journalist Anjali trusted opens the door — and it's Inspector Salvi, who closed the case in an afternoon.",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 7: The Man on the Tape" },
        { kind: "scene", sec: 6, slug: "EXT. RAIN-SLICK STREET — NIGHT", text: "Maya moves through monsoon neon, hood up, phone her only compass.", camera: "Long lens, traffic light bleeding across wet tarmac." },
        { kind: "dialogue", sec: 6, speaker: "MAYA", text: "Where am I going? If you're really her, prove it one more time. Take me somewhere only we'd know.", camera: "Phone glow under the hood." },
        { kind: "action", sec: 6, text: "The map drops a pin: a building rooftop. 'The Almost-Sky.' Their terrace, across the whole city.", camera: "Pin blooms over a satellite map." },
        { kind: "vo", sec: 7, speaker: "MAYA", text: "She's sending me to the one place we swore we'd meet if everything ever fell apart. So either she's alive — or someone read her diary down to the last word.", camera: "Reflections sliding over Maya's face in a cab window." },
        { kind: "action", sec: 5, text: "A name lands with the address: meet the journalist. Apartment 7. Go up.", camera: "Stairwell, fluorescent flicker." },
        { kind: "cliffhanger", sec: 9, text: "The door opens. It's Inspector Salvi — the officer who closed Anjali's case in a single afternoon. He smiles: 'You're late. She said you'd come.'", camera: "Push to his unreadable face. Cut." },
      ],
    },
    {
      number: 8,
      title: "Apartment 7",
      logline: "The cop who buried the case may be the only one who tried to save it.",
      runtimeSec: 0,
      cliffhanger: "Salvi: 'I closed it fast so they'd stop looking. Your sister is the one who told me to. She's been texting you — from here.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 8: Apartment 7" },
        { kind: "scene", sec: 6, slug: "INT. SAFEHOUSE APARTMENT — NIGHT", text: "Walls papered with timelines, photos, red thread. A war room built by someone who didn't sleep.", camera: "Slow pan across the obsession." },
        { kind: "dialogue", sec: 7, speaker: "MAYA", text: "You signed off on an accident. You handed me an urn. Give me one reason I don't scream.", camera: "Maya by the door, escape mapped." },
        { kind: "dialogue", sec: 8, speaker: "SALVI", text: "Because a slow case is a watched case. I closed it fast so they'd relax. So they'd stop hunting the one witness who got away.", camera: "He doesn't move toward her. He sits." },
        { kind: "dialogue", sec: 6, speaker: "MAYA", text: "What witness? Rehana? You? Who?", camera: "Maya's eyes catching the timeline." },
        { kind: "action", sec: 6, text: "On the wall, a photo of Anjali — recent, alive, holding a newspaper dated after her own funeral.", camera: "Insert: the impossible date." },
        { kind: "cliffhanger", sec: 9, text: "Salvi nods at the laptop on the desk: 'She's been texting you from this room. She wouldn't let me tell you until she was sure you weren't followed. Maya — she's in the next room.'", camera: "A door handle turns. Black." },
      ],
    },
    {
      number: 9,
      title: "The Almost-Sky",
      logline: "Maya finally meets the sender. Not everyone in the room is who they buried.",
      runtimeSec: 0,
      cliffhanger: "The woman turns around. It's Anjali's face — but Anjali is also on the laptop screen, mouthing: 'That's not me.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 9: The Almost-Sky" },
        { kind: "scene", sec: 6, slug: "INT. SAFEHOUSE — BACK ROOM — NIGHT", text: "A figure stands at the window against the city's electric haze, back to the door.", camera: "Silhouette, the skyline doing all the talking." },
        { kind: "dialogue", sec: 6, speaker: "MAYA", paren: "(voice breaking)", text: "Anjali. Turn around. Please. I've been talking to a screen for nine days. Turn around.", camera: "Maya stepping in, hand out." },
        { kind: "action", sec: 6, text: "The figure turns. It is Anjali's face — the smile, the scar above the brow, all of it.", camera: "Reveal in profile, then full." },
        { kind: "dialogue", sec: 6, speaker: "'ANJALI'", text: "I'm sorry I couldn't tell you sooner. It was the only way to keep you alive.", camera: "Warm, perfect, wrong." },
        { kind: "sfx", sec: 5, text: "On the desk, the laptop chimes. A video call connects on its own.", camera: "Insert: the screen lighting the room blue." },
        { kind: "cliffhanger", sec: 9, text: "On the laptop is Anjali — the real one, terrified, somewhere else entirely — mouthing two words at Maya: 'That's. Not. Me.' The woman in the room smiles wider.", camera: "Snap to black on the smile." },
      ],
    },
    {
      number: 10,
      title: "Sender Unknown",
      logline: "To save the sister she lost, Maya has to out-edit the people who staged a death.",
      runtimeSec: 0,
      cliffhanger: "Anjali is safe. But that night, Maya's phone lights up once more — from a number she's never seen: 'Nicely done. My turn.'",
      beats: [
        { kind: "slate", sec: 3, text: "Ep. 10: Sender Unknown" },
        { kind: "scene", sec: 6, slug: "INT. SAFEHOUSE — NIGHT", text: "Two Anjalis. One in the flesh, one on the glass. Maya, the only one who can tell a real voice from a fake.", camera: "Triangle composition: Maya at the apex." },
        { kind: "vo", sec: 7, speaker: "MAYA", text: "They built a perfect copy. Face, history, the Almost-Sky. But I clean voices for a living. And a copy always has a seam.", camera: "Maya's eyes narrowing — back in her element." },
        { kind: "dialogue", sec: 6, speaker: "MAYA", paren: "(to the impostor)", text: "Say it again. The terrace name. Say it slow.", camera: "Close on the impostor's mouth." },
        { kind: "action", sec: 6, text: "The impostor says it — flawless — but Maya hears the half-beat of someone reciting, not remembering.", camera: "Waveform overlay: a tell in the pause." },
        { kind: "action", sec: 6, text: "Salvi moves on Maya's signal. The room turns. The real Anjali's location streams in. A rescue, not a reunion.", camera: "Controlled chaos, handheld." },
        { kind: "dialogue", sec: 5, speaker: "ANJALI (LAPTOP)", paren: "(weeping, free)", text: "I knew you'd hear it. I knew you'd hear me.", camera: "Sisters split across a screen, almost touching." },
        { kind: "cliffhanger", sec: 9, text: "Dawn. Anjali is safe. Then Maya's phone glows one last time — a number she's never seen, three words: 'Nicely done. My turn.'", camera: "Pull back from the lit screen into the waking city. End of Season 1." },
      ],
    },
  ],
};
